import tournament1 from "@/assets/images/tournament-1.jpg";
import tournament2 from "@/assets/images/tournament-2.jpg";
import tournament3 from "@/assets/images/tournament-3.jpg";

export const TournamentList = [
  {
    id: 1,
    name: "Legends Showdown",
    description: "Kompetisi seru antar tim Mobile Legends terbaik.",
    date: "2024-07-15",
    location: { city: "Bandung", country: "Indonesia", address: "Jl. Merdeka No. 10" },
    prizePool: 15000,
    participants: 20,
    game: "Mobile Legends",
    image: tournament1,
  },
  {
    id: 2,
    name: "Valorant Elite Cup",
    description: "Pertarungan elite di dunia Valorant.",
    date: "2024-08-22",
    location: { city: "Surabaya", country: "Indonesia", address: "Jl. Pahlawan No. 25" },
    prizePool: 25000,
    participants: 12,
    game: "Valorant",
    image: tournament2,
  },
  {
    id: 3,
    name: "PUBG Mobile Open",
    description: "Buka untuk semua tim amatir PUBG Mobile.",
    date: "2024-09-05",
    location: { city: "Medan", country: "Indonesia", address: "Jl. Gajah Mada No. 7" },
    prizePool: 8000,
    participants: 32,
    game: "PUBG Mobile",
    image: tournament3,
  },
  {
    id: 4,
    name: "Dota 2 Regional Clash",
    description: "Turnamen regional Dota 2 se-Asia Tenggara.",
    date: "2024-10-12",
    location: { city: "Yogyakarta", country: "Indonesia", address: "Jl. Kaliurang No. 99" },
    prizePool: 30000,
    participants: 16,
    game: "Dota 2",
    image: tournament1,
  },
  {
    id: 5,
    name: "Free Fire National Cup",
    description: "Ajang bergengsi Free Fire tingkat nasional.",
    date: "2024-11-08",
    location: { city: "Semarang", country: "Indonesia", address: "Jl. Pemuda No. 55" },
    prizePool: 10000,
    participants: 40,
    game: "Free Fire",
    image: tournament2,
  },
  {
    id: 6,
    name: "Arena of Valor Challenge",
    description: "Turnamen eksklusif AoV dengan sistem gugur.",
    date: "2024-12-03",
    location: { city: "Makassar", country: "Indonesia", address: "Jl. Nusantara No. 18" },
    prizePool: 12000,
    participants: 24,
    game: "Arena of Valor",
    image: tournament3,
  },
];
